using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright © Silver Curve 2012")]
[assembly: AssemblyCompanyAttribute("Silver Curve")]
[assembly: AssemblyProductAttribute("Lord\'s Other Ground Scores")]
[assembly: AssemblyConfigurationAttribute("debug build")]

